import type { ReactNode } from "react";
import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";

const nunito = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});

export const metadata: Metadata = {
  title: "REST Countries API",
  description: "Generated by create next app",
};

interface Props {
  children: ReactNode,
};

export default function RootLayout({ children, }: Readonly<Props>) {
  return (
    <html lang="en">
      <body className={`${nunito.className} antialiased bg-cloud-white`}>
        {children}
      </body>
    </html>
  );
}
